# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tinder-analytics' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tinder-analytics
    pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'

  target 'tinder-analyticsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'tinder-analyticsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
